theme: minima
title: Space Program
author: Spacewarrior17
email: kushalrai749@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Attention! This is not actually going to take you to space :rocket:
  The Space means vast and endless, and this what I meant by my Space Program.
  I want to make an endless possibility for Human beings and make my Ideas come to life.

# social links
twitter_username: kushal4417 # DO NOT include the @ character, or else the build will fail!
github_username:  Spacewarrior17 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
